### PR TITLE
Badges Update

### PR DESCRIPTION
**Pull request by dhakalnirajan**
In Readme.md:
* License Badge added
* Repository Fork Count Badge Added
*  Made With Jupyter Notebook Badge Added
* Made With Pytorch Badge Added

### CODE REVIEW

**Review by matthewholt1 — APPROVED** [review]
Yay, copyright!

**Review by kurbus — APPROVED** [review]

**Comment by kurbus** [comment]
can we merge this already

**Comment by johnowhitaker** [comment]
@lewtun what do you think? I hadn't merged because 1) not sure we want all the badges there (maybe at the end instead where they'll break the flow less) and 2) the format will likely change soon at which point these won't fit in anyway right?

**Comment by kurbus** [comment]
> @johnowhitaker I think we can include them in the README since the migration to hf.co won't be affected. But I agree they could be placed in a better location. I think it's traditionally at the very top of the readme - WDYT?

Yeah, i could see that. But usually, badges are used to concentrate a lot of information into a small space, such as "This has the GNU GPL license" and "This uses PyTorch." By putting them at the start, this lets the readers know about it immediately, while putting it at the end makes it seem like a footnote, and a more descriptive sentence or two might perform better at the bottom, since as i mentioned above, badges are used for quick info

**Comment by lewtun** [comment]
@dhakalnirajan would you like to move these badges to the very top of the README? Then we can merge the PR :)

**Comment by dhakalnirajan** [comment]
> @dhakalnirajan would you like to move these badges to the very top of the README? Then we can merge the PR :)

Sure. Give me few minutes. After that, I will PR it.

**Comment by dhakalnirajan** [comment]
Updated the badges to the top. :)

**Comment by johnowhitaker** [comment]
Thank you :)

**Pull request merged**
